parameters:
- name: tag
- name: dockerRegistryServiceConnection
- name: imageRepository
- name: bicep
- name: resourceGroup
- name: bicepparams


steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: ${{parameters.resourceGroup}}
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --resource-group ${{parameters.resourceGroup}} --template-file "$(System.DefaultWorkingDirectory)/.azuredevops/${{parameters.bicep}}" --parameters ./.azuredevops/bicep-params/${{parameters.bicepparams}} --parameters dockerImage=$(Build.buildId) --parameters dockerRepos=${{parameters.imageRepository}}'

- task: replacetokens@3
  displayName: Replace env vars
  inputs:
    targetFiles: '.env'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '$_'
    tokenSuffix: '_$'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: true

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
    checkLatest: true
    
- task: Npm@1
  displayName: "Npm CI"
  inputs:
    command: 'ci'
    workingDir: '$(Build.SourcesDirectory)'

# TAREFA 1: Apenas Build
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    repository: '${{parameters.imageRepository}}'
    dockerfile: $(dockerfilePath)
    containerRegistry: ${{parameters.dockerRegistryServiceConnection}}
    tags: |
      ${{parameters.tag}}
    arguments: >-
      --build-arg VITE_API_URL=$(VITE_API_URL)
      --build-arg VITE_AUTHORITY=$(VITE_AUTHORITY)
      --build-arg VITE_CLIENT_ID=$(VITE_CLIENT_ID)
      --build-arg VITE_POST_LOGOUT_REDIRECT_URI=$(VITE_POST_LOGOUT_REDIRECT_URI)
      --build-arg VITE_REDIRECT_URI=$(VITE_REDIRECT_URI)

# TAREFA 2: Apenas Push
- task: Docker@2
  displayName: Push image to container registry
  inputs:
    command: push
    repository: '${{parameters.imageRepository}}'
    containerRegistry: ${{parameters.dockerRegistryServiceConnection}}
    tags: |
      ${{parameters.tag}}
