server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Tenta servir o arquivo, se não encontrar, manda para o index.html (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Cache para assets estáticos
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}